---
title: "Garmin Phoenix 5 data and analysis"
author: "André Leite"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


<!-- Para deixar fundo no rpubs.com branco como deveria ser... -->
<style>
body { background-color: white; }
pre, pre:not([class]) { background-color: white; }
</style>
<!-- Fim de "Para deixar fundo no rpubs.com branco como deveria ser..." -->


## Preliminares

### Packages used

```{r packages}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(furrr))
suppressPackageStartupMessages(library(FITfileR))
```

### Data

```{r}
treadmill_summary_day <- read_rds("../data/treadmill_summary_day.rds")
treadmill_fitday_records <- read_rds("../data/treadmill_fitday_records.rds")
```

```{r daysummary}

treadmill_summary_day %>% 
  mutate(Date = as.Date(timestamp)) %>% 
  select(-`Avg GAP`, - timestamp) %>% 
  filter(Laps != 'Summary') %>%
  kable( caption = 'Resumo dos dados por volta (1km)') %>% 
  row_spec(0, bold = TRUE, color = "white", background = "#159957") %>%
  scroll_box(height = "500px") %>% 
  kable_styling(font_size = 10) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  kable_styling(fixed_thead = TRUE) 
```


```{r recordes}

treadmill_fitday_records %>% 
  #head() %>% 
  kable(caption = 'Dados completos') %>% 
  row_spec(0, bold = TRUE, color = "white", background = "#159957") %>%
  scroll_box(height = "500px") %>%
  kable_styling(font_size = 10) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  kable_styling(fixed_thead = TRUE) 
```

### Primeiro Exercício

1. 5 minutos a 5 km/h
2. 6 km/h até completar 5km
3. 5 minutos a 5 km/h

```{r}
treadmill_summary_day %>% 
  filter(Laps != 'Summary') %>% 
  filter(as.Date(timestamp) <= "2022-08-15") %>% 
  mutate(Laps = as.integer(Laps)) %>% 
  ggplot(aes(x = Laps, y = `Avg HR`, color = factor(as.Date(timestamp)))) +
  geom_point() + geom_line() + 
  labs(color = 'Date') +
  theme_bw()
```


```{r}
treadmill_fitday_records %>% 
  mutate(Date = as.Date(timestamp)) %>% 
  filter(Date < "2022-08-16") %>% 
  group_by(Date) %>% 
  mutate(Time = as.numeric(timestamp - min(timestamp, na.rm = TRUE))) %>% 
  ggplot(aes(x = Time, y = heart_rate, color = factor(Date))) +
  geom_point(alpha = .25) + 
  geom_smooth(method = 'loess', formula = 'y ~ x', span = .5, se = FALSE) +
  theme_bw() + labs(y = 'Heart Rate', color = 'Date')
```

### Segundo Exercício

1. 5 min a 5 km/h
2. 5 min a 6 km/h
3. 5 min a 7 km/h
4. 5 min a 5 km/h

Repedido 3 vezes.


```{r}
treadmill_summary_day %>% 
  filter(Laps != 'Summary') %>% 
  filter(as.Date(timestamp) > "2022-08-15", as.Date(timestamp) < "2022-08-23") %>% 
  mutate(Laps = as.integer(Laps)) %>% 
  ggplot(aes(x = Laps, y = `Avg HR`, color = factor(as.Date(timestamp)))) +
  geom_point() + geom_line() + 
  labs(color = 'Date') +
  theme_bw()
```



```{r}
treadmill_fitday_records %>% 
  mutate(Date = as.Date(timestamp)) %>% 
  filter(Date >= "2022-08-16",  as.Date(timestamp) < "2022-08-23") %>% 
  group_by(Date) %>% 
  mutate(Time = as.numeric(timestamp - min(timestamp, na.rm = TRUE))) %>% 
  ggplot(aes(x = Time, y = heart_rate, color = factor(Date))) +
  geom_point(alpha = .25) + 
  geom_smooth(method = 'loess', formula = 'y ~ x', span = .25, se = FALSE) +
  theme_bw() + labs(y = 'Heart Rate', color = 'Date')
```


### Terceiro Exercício

1. 5 min a 5 km/h
2. 5 min a 6 km/h
3. 5 min a 7 km/h

Repedido 4 vezes. Finalizar com 5 min a 5 km/h.


```{r}
treadmill_summary_day %>% 
  filter(Laps != 'Summary') %>% 
  filter(as.Date(timestamp) > "2022-08-22", as.Date(timestamp) < "2022-08-28") %>% 
  mutate(Laps = as.integer(Laps)) %>% 
  ggplot(aes(x = Laps, y = `Avg HR`, color = factor(as.Date(timestamp)))) +
  geom_point() + geom_line() + 
  labs(color = 'Date') +
  theme_bw()
```



```{r}
treadmill_fitday_records %>% 
  mutate(Date = as.Date(timestamp)) %>% 
  filter(Date >= "2022-08-23",  as.Date(timestamp) < "2022-08-28") %>% 
  group_by(Date) %>% 
  mutate(Time = as.numeric(timestamp - min(timestamp, na.rm = TRUE))) %>% 
  ggplot(aes(x = Time, y = heart_rate, color = factor(Date))) +
  geom_point(alpha = .25) + 
  geom_smooth(method = 'loess', formula = 'y ~ x', span = .25, se = FALSE) +
  theme_bw() + labs(y = 'Heart Rate', color = 'Date')
```

